---
sudo: required
language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -q update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" -q install docker-ce

install:
  # Install molecule and docker plugin
  - pip -q install molecule docker ansible-lint flake8

script:
  - molecule test --scenario-name default
  - molecule test --scenario-name standalone-ha
  - molecule test --scenario-name mariadb
  - molecule test --scenario-name mysql