---
sudo: required
language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  # Install molecule and docker plugin
  - pip install molecule docker ansible-lint flake8

script:
  - molecule test --scenario-name default
  - molecule test --scenario-name standalone-ha
  - molecule test --scenario-name mariadb
  - molecule test --scenario-name mysql