---

- name: INCLUDE_VARS | Related to OS version
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: INCLUDE | Install Keycloak
  import_tasks: 'install/main.yml'
  tags:
    - install

- name: INCLUDE | Configure Keycloak
  import_tasks: 'configure.yml'
  tags:
    - config